- hosts: all

  tasks:
    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      ignore_errors: true
      changed_when: false

    - name: Install docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true
      become: true
      when: docker_installed.rc != 0

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      become: true

    - name: Reset ssh connection
      ansible.builtin.meta: reset_connection

    - name: Build container image locally for AMD64
      ansible.builtin.command: 
        cmd: docker buildx build --platform linux/amd64 -t evalhub:latest --load {{ playbook_dir }}/..
      delegate_to: 127.0.0.1
      changed_when: true

    - name: Export container image loca