# Generated by Django 5.2.6 on 2025-10-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.survey",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("survey", "text")},
        ),
    ]
