# Generated by Django 5.2.6 on 2025-10-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_alter_question_survey_alter_question_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
    ]
