# Generated by Django 5.2.6 on 2025-09-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Survey",
        ),
    ]
