# Generated by Django 5.2.6 on 2025-09-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.survey",
            ),
        ),
    ]
