# Generated by Django 5.2.6 on 2025-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0007_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("multiple_choice", "Multiple Choice"),
                    ("rating", "Rating Scale"),
                    ("checkbox", "Checkboxes"),
                    ("yes_no", "Yes/No"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
