# Generated by Django 5.2.6 on 2025-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0008_question_options_question_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="comment_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
