# Generated by Django 5.2.6 on 2025-10-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0010_submission_answer_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.submission",
            ),
        ),
    ]
