# Generated by Django 5.2.6 on 2025-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0011_alter_answer_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
