# Generated by Django 5.2.6 on 2025-10-09 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0012_survey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
