# Generated by Django 5.2.6 on 2025-09-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
