name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python src/manage.py test accounts surveys
    
    - name: Install Selenium
      run: |
        pip install selenium
    
    - name: Set up Firefox
      uses: browser-actions/setup-firefox@latest
    
    - name: Set up geckodriver
      uses: browser-actions/setup-geckodriver@latest
    
    - name: Run functional tests
      run: |
        python src/manage.py test functional_tests
      env:
        MOZ_HEADLESS: "1"
    
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: functional-test-screenshots
        path: src/functional_tests/screendumps/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Ansible
      run: |
        pip install ansible
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to staging
      run: |
        ansible-playbook --user=${{ secrets.VPS_USER }} \
          -i ${{ secrets.STAGING_HOST }}, \
          infra/deploy-playbook.yaml