name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python src/manage.py test accounts surveys
    
    - name: Install Selenium
      run: |
        pip install selenium
    
    - name: Install Firefox
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
    
    - name: Run functional tests
      run: |
        python src/manage.py test functional_tests
      env:
        MOZ_HEADLESS: "1"